
togglz:
  features:
    NEW_FEATURE:
      enabled: false
    EXTEND_FEATURE:
      enabled: false

  console:
    enabled: true
    secured: false
    path: /togglz-console
    use-management-port: false

  endpoint:
    enabled: true
    id: togglz
